2021-09-10 11:49:02,291 INFO    MainThread:17516 [internal.py:wandb_internal():86] W&B internal server running at pid: 17516, started at: 2021-09-10 11:49:02.282704
2021-09-10 11:49:02,298 DEBUG   HandlerThread:17516 [handler.py:handle_request():126] handle_request: run_start
2021-09-10 11:49:02,298 INFO    WriterThread:17516 [datastore.py:open_for_write():77] open: C:\Programming\rl_cooperation\Pygame_RL_cooperation\wandb\offline-run-20210910_114900-qn9k5mc0\run-qn9k5mc0.wandb
2021-09-10 11:49:02,317 DEBUG   HandlerThread:17516 [meta.py:__init__():40] meta init
2021-09-10 11:49:02,317 DEBUG   HandlerThread:17516 [meta.py:__init__():54] meta init done
2021-09-10 11:49:02,318 DEBUG   HandlerThread:17516 [meta.py:probe():211] probe
2021-09-10 11:49:02,396 DEBUG   HandlerThread:17516 [git.py:repo():33] git repository is invalid
2021-09-10 11:49:02,396 DEBUG   HandlerThread:17516 [meta.py:_save_pip():58] save pip
2021-09-10 11:49:02,398 DEBUG   HandlerThread:17516 [meta.py:_save_pip():72] save pip done
2021-09-10 11:49:02,398 DEBUG   HandlerThread:17516 [meta.py:probe():249] probe done
