2021-09-08 13:19:14,813 INFO    MainThread:4664 [wandb_setup.py:_flush():69] setting env: {}
2021-09-08 13:19:14,813 INFO    MainThread:4664 [wandb_init.py:_log_setup():342] Logging user logs to C:\Programming\rl_cooperation\Pygame_RL_cooperation\Algorithm\DQN_SpaceCannons_PER\wandb\offline-run-20210908_131914-2b8gt4j8\logs\debug.log
2021-09-08 13:19:14,814 INFO    MainThread:4664 [wandb_init.py:_log_setup():343] Logging internal logs to C:\Programming\rl_cooperation\Pygame_RL_cooperation\Algorithm\DQN_SpaceCannons_PER\wandb\offline-run-20210908_131914-2b8gt4j8\logs\debug-internal.log
2021-09-08 13:19:14,815 INFO    MainThread:4664 [wandb_init.py:init():375] calling init triggers
2021-09-08 13:19:14,815 INFO    MainThread:4664 [wandb_init.py:init():380] wandb.init called with sweep_config: {}
config: {}
2021-09-08 13:19:14,816 INFO    MainThread:4664 [wandb_init.py:init():424] starting backend
2021-09-08 13:19:14,816 INFO    MainThread:4664 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=spawn, using: spawn
2021-09-08 13:19:14,827 INFO    MainThread:4664 [backend.py:ensure_launched():135] starting backend process...
2021-09-08 13:19:15,377 INFO    MainThread:4664 [backend.py:ensure_launched():139] started backend process with pid: 16288
2021-09-08 13:19:15,379 INFO    MainThread:4664 [wandb_init.py:init():429] backend started and connected
2021-09-08 13:19:15,383 INFO    MainThread:4664 [wandb_init.py:init():477] updated telemetry
2021-09-08 13:19:15,387 INFO    MainThread:4664 [wandb_init.py:init():540] starting run threads in backend
2021-09-08 13:19:16,652 INFO    MainThread:4664 [wandb_run.py:_console_start():1601] atexit reg
2021-09-08 13:19:16,653 INFO    MainThread:4664 [wandb_run.py:_redirect():1475] redirect: SettingsConsole.WRAP
2021-09-08 13:19:16,654 INFO    MainThread:4664 [wandb_run.py:_redirect():1512] Wrapping output streams.
2021-09-08 13:19:16,657 INFO    MainThread:4664 [wandb_run.py:_redirect():1536] Redirects installed.
2021-09-08 13:19:16,657 INFO    MainThread:4664 [wandb_init.py:init():565] run started, returning control to user process
2021-09-08 13:19:25,433 INFO    MainThread:4664 [wandb_run.py:_atexit_cleanup():1571] got exitcode: 1
2021-09-08 13:19:25,434 INFO    MainThread:4664 [wandb_run.py:_restore():1543] restore
2021-09-08 13:19:25,582 INFO    MainThread:4664 [wandb_run.py:_wait_for_finish():1693] got exit ret: 
2021-09-08 13:19:25,727 INFO    MainThread:4664 [wandb_run.py:_wait_for_finish():1693] got exit ret: 
2021-09-08 13:19:25,834 INFO    MainThread:4664 [wandb_run.py:_wait_for_finish():1693] got exit ret: done: true
exit_result {
}

