2021-09-10 11:53:08,064 INFO    MainThread:36160 [internal.py:wandb_internal():86] W&B internal server running at pid: 36160, started at: 2021-09-10 11:53:08.055977
2021-09-10 11:53:08,072 INFO    WriterThread:36160 [datastore.py:open_for_write():77] open: C:\Programming\rl_cooperation\Pygame_RL_cooperation\wandb\offline-run-20210910_115306-24gcgsva\run-24gcgsva.wandb
2021-09-10 11:53:08,073 DEBUG   HandlerThread:36160 [handler.py:handle_request():126] handle_request: run_start
2021-09-10 11:53:08,092 DEBUG   HandlerThread:36160 [meta.py:__init__():40] meta init
2021-09-10 11:53:08,092 DEBUG   HandlerThread:36160 [meta.py:__init__():54] meta init done
2021-09-10 11:53:08,092 DEBUG   HandlerThread:36160 [meta.py:probe():211] probe
2021-09-10 11:53:08,167 DEBUG   HandlerThread:36160 [git.py:repo():33] git repository is invalid
2021-09-10 11:53:08,167 DEBUG   HandlerThread:36160 [meta.py:_save_pip():58] save pip
2021-09-10 11:53:08,168 DEBUG   HandlerThread:36160 [meta.py:_save_pip():72] save pip done
2021-09-10 11:53:08,169 DEBUG   HandlerThread:36160 [meta.py:probe():249] probe done
