

1989it [00:03, 610.37it/s]C:\Programming\rl_cooperation\lib\site-packages\torch\nn\modules\loss.py:907: UserWarning: Using a target size (torch.Size([1000, 1000])) that is different to the input size (torch.Size([1000])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.smooth_l1_loss(input, target, reduction=self.reduction, beta=self.beta)
2194it [00:04, 193.12it/s]Traceback (most recent call last):
  File "c:\Programming\rl_cooperation\DQN_breakout\agent.PY", line 151, in <module>
    main(False)
  File "c:\Programming\rl_cooperation\DQN_breakout\agent.PY", line 120, in main
    action = m(torch.Tensor(last_observation)).unsqueeze(0).max(-1)[-1].item()
  File "C:\Programming\rl_cooperation\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "c:\Programming\rl_cooperation\DQN_breakout\models.py", line 52, in forward
    convLat = self.ConvNet(x/255.0)
  File "C:\Programming\rl_cooperation\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Programming\rl_cooperation\lib\site-packages\torch\nn\modules\container.py", line 119, in forward
    input = module(input)
  File "C:\Programming\rl_cooperation\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Programming\rl_cooperation\lib\site-packages\torch\nn\modules\conv.py", line 399, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\Programming\rl_cooperation\lib\site-packages\torch\nn\modules\conv.py", line 395, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Expected 4-dimensional input for 4-dimensional weight [16, 4, 8, 8], but got 3-dimensional input of size [4, 84, 84] instead