2021-09-08 13:23:33,166 INFO    MainThread:19264 [internal.py:wandb_internal():86] W&B internal server running at pid: 19264, started at: 2021-09-08 13:23:33.154081
2021-09-08 13:23:33,172 INFO    WriterThread:19264 [datastore.py:open_for_write():77] open: C:\Programming\rl_cooperation\Pygame_RL_cooperation\Algorithm\DQN_SpaceCannons_PER\wandb\offline-run-20210908_132331-r3f0cnzs\run-r3f0cnzs.wandb
2021-09-08 13:23:33,173 DEBUG   HandlerThread:19264 [handler.py:handle_request():126] handle_request: run_start
2021-09-08 13:23:33,192 DEBUG   HandlerThread:19264 [meta.py:__init__():40] meta init
2021-09-08 13:23:33,193 DEBUG   HandlerThread:19264 [meta.py:__init__():54] meta init done
2021-09-08 13:23:33,193 DEBUG   HandlerThread:19264 [meta.py:probe():211] probe
2021-09-08 13:23:33,266 DEBUG   HandlerThread:19264 [git.py:repo():33] git repository is invalid
2021-09-08 13:23:33,266 DEBUG   HandlerThread:19264 [meta.py:_save_pip():58] save pip
2021-09-08 13:23:33,267 DEBUG   HandlerThread:19264 [meta.py:_save_pip():72] save pip done
2021-09-08 13:23:33,267 DEBUG   HandlerThread:19264 [meta.py:probe():249] probe done
