2021-09-11 12:51:46,889 INFO    MainThread:14900 [internal.py:wandb_internal():86] W&B internal server running at pid: 14900, started at: 2021-09-11 12:51:46.880407
2021-09-11 12:51:46,897 INFO    WriterThread:14900 [datastore.py:open_for_write():77] open: C:\Programming\rl_cooperation\Pygame_RL_cooperation\wandb\offline-run-20210911_125145-2i8flci8\run-2i8flci8.wandb
2021-09-11 12:51:46,897 DEBUG   HandlerThread:14900 [handler.py:handle_request():126] handle_request: run_start
2021-09-11 12:51:46,919 DEBUG   HandlerThread:14900 [meta.py:__init__():40] meta init
2021-09-11 12:51:46,919 DEBUG   HandlerThread:14900 [meta.py:__init__():54] meta init done
2021-09-11 12:51:46,920 DEBUG   HandlerThread:14900 [meta.py:probe():211] probe
2021-09-11 12:51:47,014 DEBUG   HandlerThread:14900 [git.py:repo():33] git repository is invalid
2021-09-11 12:51:47,014 DEBUG   HandlerThread:14900 [meta.py:_save_pip():58] save pip
2021-09-11 12:51:47,015 DEBUG   HandlerThread:14900 [meta.py:_save_pip():72] save pip done
2021-09-11 12:51:47,016 DEBUG   HandlerThread:14900 [meta.py:probe():249] probe done
